### PR TITLE
Add bot whitelist

### LINKED ISSUE #22: Gnitpick fails with dependabot commits
We had a problem where dependabot makes a commit automatically for dependency update. The commit failed gnitpick tests with the following:

```
Author name 'dependabot[bot]' does not start with an uppercase letter
```

It would be nice to have a whitelist of common bots or something other logic like `if "bot" in name => ok`. Please consider the pros and cons of different solutions.

### PR DESCRIPTION
**Pull request by frimro**
- Fixes #22, by adding a bot whitelist
- Makes code more pythonic

### CODE REVIEW

**Comment by frimro** [comment]
There is also the argument whether or not the whitelist should be supplied as a command line argument instead of being hard-coded as a variable. Discussion is welcome.

**Review by elguitar — CHANGES_REQUESTED** [review]
Good that you mentioned the possibility of having the bot whitelist as a command line argument. To me, it seems like the most maintainable option. People should be able to integrate `gnitpick` to their pipelines without needing to update the code to match their bots.

The refactorings look great :)

**Comment by frimro** [comment]
Moved the whitelist to a command line argument. Made some refactoring on the argparse as well.

**Review by elguitar — APPROVED** [review]
LGTM! Feel free to merge

**Pull request merged**
